repositorioecommerce/ecommerce/apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('listar/', views.Listar_articulos, name = 'path_listar_articulos'),

    path('detalle/<int:pk>', views.Detalle_Articulo_Clase.as_view(), name = 'path_detalle_articulo'),

    #CREAR
    path('crear/', views.Crear_Articulo.as_view(), name = 'path_crear_articulo'),

    #MODIFICAR

    path('modificar/<int:pk>', views.Modificar_Articulo.as_view(), name= 'path_modificar_articulo'),
    
    #ELIMINAR

    path('eliminar/<int:pk>', views.Eliminar_Articulo.as_view(), name= 'path_eliminar_articulo'),

    #FILTROS

    path('filtrarxcategoria/<int:pk>', views.Filtro_Categoria, name= 'path_filtrado_categoria'),

    path('buscador/', views.Buscador, name='path_buscador'),
    
    path('fecha/<str:orden>/', views.Filtro_Fecha, name='path_filtrado_fecha'),

    path ('comentar/<int:pk>', views.comentar, name= 'path_comentar'),

    path('borrar_comentario/<int:pk>/', views.borrar_comentario, name='path_borrar_comentario'),

    path('alfabetico/<str:orden>/', views.Filtro_Alfabetico, name='path_filtrado_alfabetico'),
]
    

repositorioecommerce/ecommerce/apps/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth
app_name = 'usuarios'

urlpatterns = [

    path('login/', auth.LoginView.as_view(template_name = 'usuarios/login.html'), name = 'path_login'),
    
    path('logout/', auth.LogoutView.as_view(), name = 'path_logout')

]
     

repositorioecommerce/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

path('', views.Home, name = 'path_home'),
path('contacto/', views.Contacto, name = 'path_contacto'),
path('sobre_nosotros/', views.Sobre_Nosotros, name = 'path_sobre_nosotros'),
#enlazamos con las apps
path('blog/', include('blog.urls')),
path('usuarios/', include('usuarios.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repositorioecommerce/ecommerce/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    nombre_categoria = models.CharField(max_length=60)
    descripcion = models.TextField(null = True, blank=True)

    def __str__(self):
        return self.nombre_categoria

class Articulo(models.Model):
    titulo = models.CharField(max_length=60)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to='articulos/',max_length=255, null=True, blank=True)
    fecha_publicacion = models.DateTimeField(auto_now=True)
    fecha_actualizacion = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE, related_name="comentarios")

    def __str__(self):
        return f"Comentario de: {self.autor.username}"

repositorioecommerce/ecommerce/apps/blog/forms.py
from django import forms
from .models import Articulo

class FormularioCrearArticulo(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['titulo', 'contenido', 'imagen', 'categoria']
        
        # ESTO ES MAGIA: Le decimos a Django "Ponele la clase CSS 'input-hacker' a todo"
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'input-hacker', 'placeholder': 'Título del Informe...'}),
            'contenido': forms.Textarea(attrs={'class': 'input-hacker', 'rows': 5, 'placeholder': 'Desarrollo del contenido...'}),
            'categoria': forms.Select(attrs={'class': 'input-hacker'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'input-hacker'}),
        }

class FormularioModificarArticulo(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = ['titulo', 'contenido', 'imagen', 'categoria']
        
        # Lo mismo para modificar, mantenemos el estilo
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'input-hacker'}),
            'contenido': forms.Textarea(attrs={'class': 'input-hacker', 'rows': 5}),
            'categoria': forms.Select(attrs={'class': 'input-hacker'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'input-hacker'}),
        }

repositorioecommerce/ecommerce/apps/blog/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from .models import Articulo, Categoria, Comentario
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import FormularioCrearArticulo, FormularioModificarArticulo
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def Listar_articulos(request):
    todos_articulos = Articulo.objects.all().order_by('-fecha_publicacion')
    categorias = Categoria.objects.all()
    context = {}
    context['articulos'] = todos_articulos
    context['categorias'] = categorias
    
    return render(request, 'blog/listar.html', context)

class Detalle_Articulo_Clase(DetailView):
    model = Articulo
    template_name = 'blog/detalle.html'

def Filtro_Categoria(request, pk):
    ca = Categoria.objects.get(pk = pk)
    ar = Articulo.objects.filter(categoria = ca)
    categorias = Categoria.objects.all()
    context = {}
    context['articulos'] = ar
    context['categorias'] = categorias

    return render(request, 'blog/listar.html', context)

def Buscador(request):
    if request.method == 'POST':
        busqueda = request.POST['busqueda']
        articulos = Articulo.objects.filter(titulo__icontains=busqueda)
        categorias = Categoria.objects.all()
        context = {}
        context['articulos'] = articulos
        context['categorias'] = categorias
        return render(request, 'blog/listar.html', context)
    
    return render(request, 'blog/listar.html')

def Filtro_Fecha(request, orden):
    if orden == 'antiguo':
        articulos = Articulo.objects.all().order_by('fecha_publicacion')
    else:
        articulos = Articulo.objects.all().order_by('-fecha_publicacion')
    
    categorias = Categoria.objects.all()


    context = {}


    context['articulos'] = articulos
    context['categorias'] = categorias

    return render(request, 'blog/listar.html', context)


class Crear_Articulo(LoginRequiredMixin, CreateView):
    model = Articulo
    template_name = 'blog/crear.html'
    form_class = FormularioCrearArticulo
    success_url = reverse_lazy('blog:path_listar_articulos')

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_staff


class Modificar_Articulo(LoginRequiredMixin, UpdateView):
    model = Articulo
    template_name = 'blog/modificar.html'
    form_class = FormularioModificarArticulo
    success_url = reverse_lazy('blog:path_listar_articulos')

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)


class Eliminar_Articulo(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Articulo
    template_name = 'blog/eliminar.html'
    success_url = reverse_lazy('blog:path_listar_articulos')

    def test_func(self):
        articulo = self.get_object()
        return self.request.user == articulo.autor or self.request.user.is_staff

#LOGICA DE COMENTARIOS

@login_required 
def comentar(request, pk):
    articulo_seleccionado = Articulo.objects.get(pk=pk)
    usuario_actual = request.user
    
    texto_ingresado = request.POST.get('texto_comentado') 

    Comentario.objects.create(
        contenido = texto_ingresado, 
        autor = usuario_actual, 
        articulo = articulo_seleccionado
    )
    return HttpResponseRedirect(reverse_lazy('blog:path_detalle_articulo', kwargs={'pk': pk}))

@login_required 
def borrar_comentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    id_articulo = comentario.articulo.pk

    if request.user == comentario.autor or request.user.is_staff:
        comentario.delete()

    return redirect('blog:path_detalle_articulo', pk=id_articulo)

def Filtro_Alfabetico(request, orden):
    if orden == 'az':
        # Orden ascendente (A-Z)
        articulos = Articulo.objects.all().order_by('titulo')
    elif orden == 'za':
        # Orden descendente (Z-A)
        articulos = Articulo.objects.all().order_by('-titulo')
    else:
        articulos = Articulo.objects.all()

    categorias = Categoria.objects.all()
    
    context = {
        'articulos': articulos,
        'categorias': categorias
    }

    return render(request, 'blog/listar.html', context)

repositorioecommerce/ecommerce/templates/blog/detalle.html
{% extends 'general/base.html' %}
{% load static %}

{% block contenido %}

<div style="max-width: 900px; margin: 0 auto; padding: 40px 20px;">

    {% if user == articulo.autor or user.is_staff %}
    <div style="
        border: 1px dashed #d63384; 
        background-color: rgba(214, 51, 132, 0.05); 
        padding: 15px; 
        margin-bottom: 30px; 
        border-radius: 6px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    ">
        <span style="color: #d63384; font-weight: bold; font-family: monospace;">
            [⚠️ MODO EDICIÓN]
        </span>

        <div>
            <a href="{% url 'blog:path_modificar_articulo' articulo.pk %}" style="
                color: #ffc107; 
                text-decoration: none; 
                border: 1px solid #ffc107; 
                padding: 5px 15px; 
                margin-right: 10px; 
                font-size: 0.9rem;
                border-radius: 4px;
            ">✎ EDITAR</a>

            <a href="{% url 'blog:path_eliminar_articulo' articulo.pk %}" style="
                color: #ff4444; 
                text-decoration: none; 
                border: 1px solid #ff4444; 
                padding: 5px 15px; 
                font-size: 0.9rem;
                border-radius: 4px;
            ">X ELIMINAR</a>
        </div>
    </div>
    {% endif %}

    <header style="border-bottom: 1px solid #30363d; padding-bottom: 20px; margin-bottom: 30px;">

        <span style="
            background-color: var(--neon-green); 
            color: black; 
            padding: 4px 8px; 
            font-size: 0.8rem; 
            font-weight: bold; 
            border-radius: 2px;
        ">
            {{ articulo.categoria|upper }}
        </span>

        <h1 style="
            font-size: 2.5rem; 
            margin-top: 15px; 
            margin-bottom: 10px; 
            color: white; 
            line-height: 1.2;
        ">
            {{ articulo.titulo }}
        </h1>

        <div style="color: #8b949e; font-size: 0.9rem; font-family: 'Courier New', monospace;">
            <span>> AUTHOR: <strong style="color: #c9d1d9;">{{ articulo.autor.username }}</strong></span>
            <span style="margin: 0 10px;">|</span>
            <span>> DATE: {{ articulo.fecha_publicacion|date:"d M Y" }}</span>
            {% if articulo.fecha_actualizacion != articulo.fecha_publicacion %}
            <span style="margin: 0 10px;">|</span>
            <span>(Updated: {{ articulo.fecha_actualizacion|date:"d M Y" }})</span>
            {% endif %}
        </div>
    </header>

    {% if articulo.imagen %}
    <div style="margin-bottom: 30px; border: 1px solid #30363d; padding: 5px;">
        <img src="{{ articulo.imagen.url }}" alt="{{ articulo.titulo }}" style="
                width: 100%; 
                height: 450px; 
                object-fit: cover; 
                object-position: center; 
                display: block;
            ">
    </div>
    {% endif %}

    <article style="
        font-size: 1.1rem; 
        line-height: 1.8; 
        color: #c9d1d9; 
        margin-bottom: 60px;
        white-space: pre-wrap;
    ">
        {{ articulo.contenido }}
    </article>


    <section>
        <h3 style="
            border-left: 4px solid var(--neon-green); 
            padding-left: 15px; 
            color: white; 
            margin-bottom: 30px;
        ">
            REGISTRO DE COMENTARIOS_
        </h3>

        <div style="margin-bottom: 40px;">
            {% for c in articulo.comentarios.all %}
            <div style="
                    background-color: #0d1117; 
                    border: 1px solid #30363d; 
                    padding: 20px; 
                    margin-bottom: 15px; 
                    border-radius: 6px;
                    position: relative;
                ">
                <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
                    <span style="color: var(--neon-green); font-weight: bold; font-size: 0.9rem;">
                        USER: {{ c.autor.username }}
                    </span>
                    <small style="color: gray;">{{ c.fecha_creacion|date:"d/m/Y H:i" }}</small>
                </div>

                <p style="color: #c9d1d9; margin: 0;">{{ c.contenido }}</p>

                {% if user == c.autor or user.is_staff %}
                <div style="margin-top: 15px; text-align: right;">
                    <a href="{% url 'blog:path_borrar_comentario' c.pk %}" style="
                            color: #ff4444; 
                            font-size: 0.8rem; 
                            text-decoration: none; 
                            border: 1px solid #ff4444; 
                            padding: 2px 8px; 
                            border-radius: 3px;
                            transition: 0.3s;
                        " onmouseover="this.style.backgroundColor='#ff4444'; this.style.color='white';"
                        onmouseout="this.style.backgroundColor='transparent'; this.style.color='#ff4444';">
                        [X] ELIMINAR DATOS
                    </a>
                </div>
                {% endif %}
            </div>
            {% empty %}
            <div style="padding: 20px; text-align: center; border: 1px dashed gray; color: gray;">
                No se han encontrado registros en este articulo.
            </div>
            {% endfor %}
        </div>

        {% if user.is_authenticated %}
        <div
            style="background-color: #161b22; padding: 25px; border-radius: 8px; border-top: 2px solid var(--neon-green);">
            <label style="color: var(--neon-green); font-weight: bold; display: block; margin-bottom: 10px;">
                > ESCRIBIR NUEVO COMENTARIO:
            </label>

            <form method="POST" action="{% url 'blog:path_comentar' articulo.pk %}">
                {% csrf_token %}
                <textarea name="texto_comentado" class="input-hacker" rows="4" placeholder="Ingrese su análisis..."
                    style="resize: vertical;"></textarea>

                <button type="submit" class="btn-login" style="margin-top: 15px; width: auto; padding: 10px 40px;">
                    ENVIAR
                </button>
            </form>
        </div>
        {% else %}
        <div style="text-align: center; margin-top: 30px;">
            <p style="color: #8b949e;">Acceso de escritura denegado. Identifíquese para participar.</p>
            <a href="{% url 'usuarios:path_login' %}" style="
                    color: var(--neon-green); 
                    border: 1px solid var(--neon-green); 
                    padding: 10px 20px; 
                    text-decoration: none; 
                    font-weight: bold;
                ">
                > INICIAR SESIÓN
            </a>
        </div>
        {% endif %}

    </section>

</div>

{% endblock contenido %}

repositorioecommerce/ecommerce/templates/blog/listar.html
{% extends 'general/base.html' %}

{% block contenido %}

<div class="blog-container">

    <aside class="barra-lateral">

        <h3 class="titulo-filtro">PANEL DE CONTROL</h3>

        <form method="POST" action="{% url 'blog:path_buscador' %}">
            {% csrf_token %}
            <label style="color:var(--neon-green); font-weight:bold;">BÚSQUEDA:</label>

            <div style="margin-top: 5px; margin-bottom: 10px;">
                <input type="text" name="busqueda" class="input-hacker" placeholder="Escribe el título...">
            </div>

            <button type="submit" class="btn-login" style="width:100%;">🔎 BUSCAR</button>
        </form>

        <hr style="border-color: #30363d; margin: 20px 0;">

        <label style="color:var(--neon-green); font-weight:bold; margin-bottom: 10px; display:block;">
            ORDENAR POR FECHA:
        </label>

        <div style="display: flex; gap: 10px; flex-direction: column;">
            <a href="{% url 'blog:path_filtrado_fecha' 'nuevo' %}" class="btn-orden">
                ⬇️ Más Recientes
            </a>

            <a href="{% url 'blog:path_filtrado_fecha' 'antiguo' %}" class="btn-orden">
                ⬆️ Más Antiguos
            </a>
        </div>

        <hr style="border-color: #30363d; margin: 20px 0;">

        <label style="color:var(--neon-green); font-weight:bold; margin-bottom: 10px; display:block;">
            ORDEN ALFABÉTICO:
        </label>

        <div style="display: flex; gap: 10px; flex-direction: column;">
            <a href="{% url 'blog:path_filtrado_alfabetico' 'az' %}" class="btn-orden">
                🔤 Título (A - Z)
            </a>

            <a href="{% url 'blog:path_filtrado_alfabetico' 'za' %}" class="btn-orden">
                🔠 Título (Z - A)
            </a>
        </div>

        <hr style="border-color: #30363d; margin: 20px 0;">

        <label style="color:var(--neon-green); font-weight:bold;">CATEGORÍAS:</label>
        <div class="dropdown-container" style="margin-top: 5px;">
            <button class="btn-dropdown">📂 Seleccionar Categoría ▼</button>
            <div class="dropdown-content">
                <a href="{% url 'blog:path_listar_articulos' %}">[X] Ver todo</a>
                {% for c in categorias %}
                <a href="{% url 'blog:path_filtrado_categoria' c.pk %}">> {{ c.nombre_categoria }}</a>
                {% endfor %}
            </div>
        </div>

        {% if user.is_authenticated %}
        <hr style="border-color: #d63384; margin: 30px 0;">

        <label style="color: #d63384; font-weight:bold; display:block; margin-bottom:10px;">
            CONTRIBUIR:
        </label>

        <a href="{% url 'blog:path_crear_articulo' %}" class="btn-login" style="
                display:block; 
                text-align:center; 
                border: 1px solid #d63384; 
                color: #d63384;
                background-color: rgba(214, 51, 132, 0.05);
            " onmouseover="this.style.backgroundColor='#d63384'; this.style.color='white';"
            onmouseout="this.style.backgroundColor='transparent'; this.style.color='#d63384';">
            + NUEVO ARTÍCULO
        </a>
        {% endif %}

    </aside>

    <section class="columna-articulos">

        <h1 class="titulo-seccion">ARTICULOS</h1>

        <div class="grilla-articulos">

            {% for a in articulos %}

            <article class="card">

                {% if a.imagen %}
                <div class="card-img-container">
                    <img src="{{ a.imagen.url }}" alt="{{ a.titulo }}">
                </div>
                {% endif %}

                <div class="card-contenido">
                    <h3>{{ a.titulo }}</h3>

                    <span class="card-fecha" style="font-size: 0.8em; color: gray;">
                        {{ a.fecha_publicacion|date:"d/m/Y" }}
                    </span>

                    <a href="{% url 'blog:path_detalle_articulo' a.pk %}" class="btn-leer">
                        ACCEDER AL ARTICULO >
                    </a>

                    {% if user == a.autor or user.is_staff %}
                    <div class="acciones-admin"
                        style="margin-top: 10px; border-top: 1px solid #30363d; padding-top: 10px;">
                        <a href="{% url 'blog:path_modificar_articulo' a.pk %}"
                            style="color: yellow; margin-right: 10px; text-decoration: none; font-size: 0.9rem;">
                            ✏️ Modificar
                        </a>
                        <a href="{% url 'blog:path_eliminar_articulo' a.pk %}"
                            style="color: red; text-decoration: none; font-size: 0.9rem;">
                            🗑️ Eliminar
                        </a>
                    </div>
                    {% endif %}
                </div>

            </article>

            {% empty %}
            <p>No hay artículos cargados en el sistema.</p>
            {% endfor %}

        </div>

    </section>

</div>

{% endblock contenido %}